import java.util.ArrayList;

public class TweetClass {
	
	private String tweetAuthor;
	private String tweetContent;
	
	public TweetClass() {
		
		tweetContent = "";
		tweetAuthor = "";
		
	}
	
	public TweetClass(String tC, String tA) {
		
		setTweetContent(tC);
		setTweetAuthor(tA);
		
	}
	
	public String getTweetContent() {
		return tweetContent;
	}
	
	public void setTweetContent(String tweetContent) {
		this.tweetContent = tweetContent;
	}
	
	public String getTweetAuthor() {
		return tweetAuthor;
	}
	
	public void setTweetAuthor(String tweetAuthor) {
		this.tweetAuthor = tweetAuthor;
	}
	
	public boolean contains(String s) {
		
		return getTweetContent().contains(s);
	}

	public String toString() {
		return getTweetContent() + " by: " + getTweetAuthor() + "\n";
	}
	
	public static void main(String[] args) {
		
		TweetClass testTweet = new TweetClass();
		
		testTweet.setTweetContent("It is now possible to learn about a person's mobility preferences from data generated by their smartphone");
		testTweet.setTweetAuthor("someperson");
		
		System.out.println(testTweet);
		
	}
	
}
